version: '3'

services:
    db:
        image: mysql:5.7
        container_name: db_mysql
        environment:
            MYSQL_DATABASE: weather_forecast
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - "9906:3306"
        expose:
            - "3306"
        volumes:
            - db_app:/var/lib/mysql
        networks:
            - dev
    webapp:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: webapp
        environment:
            - DATABASE_URL="mysql://root:@db:3306/weather_forecast"
        depends_on:
            - db
        ports:
            - "8100:80"
        volumes:
            - ./:/var/www/app
        links:
            - db
        networks:
            - dev

volumes:
    db_app:

networks:
    dev: